

services:
  mysql:
    image: mysql:8.0
    container_name: fcs-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fcsdb
      MYSQL_USER: fcsuser
      MYSQL_PASSWORD: fcspassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:

